compile: longest-substring-without-repeating-characters.c
	@gcc -o longest-substring-without-repeating-characters longest-substring-without-repeating-characters.c

test: compile
	@./longest-substring-without-repeating-characters

clean:
	@rm -f longest-substring-without-repeating-characters
